package org.aion.harness.util;

import java.io.File;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import org.aion.harness.misc.Assumptions;
import org.aion.harness.result.Result;
import org.apache.commons.io.FileUtils;

/**
 * A class that is used to set up and manage the log files generated by an active node.
 */
public final class LogManager {
    private File currentOutputLog;
    private File currentErrorLog;

    /**
     * This method creates the necessary output and error log files in the logs directory. If this
     * directory does not exist yet, then this method creates it.
     *
     * This method will also archive any outdated logs. That is, it will collect any log files
     * currently in the logs directly and place them in an archive directory. Once more, if this
     * archive directory does not exist then it will be created.
     *
     * After calling this method successfully, the current output and error log files should exist.
     *
     * @return A result indicating the successfulness of this call.
     */
    public Result setupLogFiles() {

        // Set the logs to null so we can trust these variables after multiple calls.
        this.currentOutputLog = null;
        this.currentErrorLog = null;

        if (!createLogsDirectoryIfDoesNotExist()) {
            return Result.unsuccessful(Assumptions.PRODUCTION_ERROR_STATUS, "failed to create log directory");
        }

        try {
            // archive any old log files.
            archiveLogs();

            // create the new log files.
            this.currentOutputLog = createNewStdoutLog();
            if (this.currentOutputLog == null) {
                return Result.unsuccessful(Assumptions.PRODUCTION_ERROR_STATUS, "failed to create stdout log");
            }

            this.currentErrorLog = createNewStderrLog();
            if (this.currentErrorLog == null) {
                return Result.unsuccessful(Assumptions.PRODUCTION_ERROR_STATUS, "failed to create stderr log");
            }
        } catch (IOException e) {
            return Result.unsuccessful(Assumptions.PRODUCTION_ERROR_STATUS, (e.getMessage() == null) ? e.toString() : e.getMessage());
        }

        return Result.successful();
    }

    /**
     * Returns the current log file used to log a node's output, or null if no such file exists yet.
     *
     * @return The current output log file.
     */
    public File getCurrentOutputLogFile() {
        return this.currentOutputLog;
    }

    /**
     * Returns the current log file used to log a node's errors, or null if no such file exists yet.
     *
     * @return The current error log file.
     */
    public File getCurrentErrorLogFile() {
        return this.currentErrorLog;
    }

    /**
     * creates the logs directory if it does not exist, otherwise does nothing.
     */
    private boolean createLogsDirectoryIfDoesNotExist() {
        return (NodeFileManager.getLogsDirectory().exists()) ? true : NodeFileManager.getLogsDirectory().mkdir();
    }

    /**
     * Moves any outstanding log files into the archived directory if they exist.
     */
    private void archiveLogs() throws IOException {
        File[] logEntries = NodeFileManager.getLogsDirectory().listFiles();

        if (logEntries == null) {
            return;
        }

        for (File entry : logEntries) {
            if (entry.isFile()) {
                FileUtils.moveFileToDirectory(entry, NodeFileManager.getLogArchiveDirectory(), true);
            }
        }
    }

    /**
     * Creates the stdout log file in the logs directory and returns this file if successful, otherwise returns null.
     *
     * ASSUMPTION: logs directory exists.
     */
    private File createNewStdoutLog() throws IOException {
        File stdoutLogFile = new File(NodeFileManager.getLogsDirectory() + File.separator + createLogFilename("out"));
        return (stdoutLogFile.createNewFile()) ? stdoutLogFile : null;
    }

    /**
     * Creates the stderr log file in the logs directory and returns this file if successful, otherwise returns null.
     *
     * ASSUMPTION: logs directory exists.
     */
    private File createNewStderrLog() throws IOException {
        File stdoutLogFile = new File(NodeFileManager.getLogsDirectory() + File.separator + createLogFilename("err"));
        return (stdoutLogFile.createNewFile()) ? stdoutLogFile : null;
    }

    /**
     * Creates a filename following a specific log file naming convention with the option of
     * specifying a postfix to make the name unique.
     */
    private String createLogFilename(String postfix) {
        Date currentDate = new Date(System.currentTimeMillis());
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(currentDate);

        return calendar.get(Calendar.YEAR) + "-"
            + String.format("%02d", (calendar.get(Calendar.MONTH) +  1)) + "-"
            + String.format("%02d", calendar.get(Calendar.DAY_OF_MONTH)) + "-"
            + String.format("%02d", calendar.get(Calendar.HOUR_OF_DAY)) + ":"
            + String.format("%02d", calendar.get(Calendar.MINUTE)) + ":"
            + String.format("%02d", calendar.get(Calendar.SECOND)) + "-"
            + postfix + ".txt";
    }

}
